# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BEJWCY_3apX37-Y0mbKhnnVcP-1kaSh5
"""

import streamlit as st
import pandas as pd
import altair as alt


st.title("Cantidad de Terremotos en Chile")


st.sidebar.title("Información adicional")
st.sidebar.write("Esto es una barra lateral donde puedes encontrar recomendaciones y más.")


if st.sidebar.button("Haz clic para ver tips"):
    st.sidebar.write("""
    - Mantente alejado de ventanas, espejos y muebles grandes.
    - Si el edificio es estructuralmente endeble, sal de él lo más rápido posible.
    - Si estás afuera, corre a un área abierta lejos de edificios y cables eléctricos que puedan caer.
    """)

user_input = st.sidebar.text_input("Escribe algo aquí:")
if user_input:
    st.sidebar.write(f"Has escrito: {user_input}")


st.subheader("Estadísticas de terremotos en Chile (2010-2023)")


data = {
    "Años": [2010, 2012, 2014, 2016, 2018, 2020, 2022, 2023],
    "Cantidad de Terremotos": [300, 1500, 2000, 2500, 2300, 2500, 3000, 2800]
}
df = pd.DataFrame(data)


st.write(df)


chart = alt.Chart(df).mark_bar().encode(
    x='Años:O',
    y='Cantidad de Terremotos:Q',
    color='Años:O',
    tooltip=['Años', 'Cantidad de Terremotos']
).properties(
    title="Cantidad de Terremotos por Año en Chile"
)


st.altair_chart(chart, use_container_width=True)